server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5434
    username: postgres
    password: postgres
    name: postgres
    pool:
      max-size: 100
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:postgresql://localhost:5434/postgres
    user: postgres
    password: postgres